# Generated by Django 5.0.6 on 2024-06-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_about_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, max_length=100)),
                ('university', models.CharField(blank=True, max_length=100)),
                ('fromeYear', models.CharField(blank=True, max_length=10)),
                ('toYear', models.CharField(blank=True, max_length=10)),
                ('desc', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
