# Generated by Django 5.0.6 on 2024-06-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='desc',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
