# Generated by Django 5.0.6 on 2024-06-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_education_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('fromYear', models.CharField(blank=True, max_length=100)),
                ('toYear', models.CharField(blank=True, max_length=100)),
                ('desc', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='education',
            old_name='fromeYear',
            new_name='fromYear',
        ),
    ]
