# Generated by Django 5.0.6 on 2024-06-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_experience_rename_fromeyear_education_fromyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('team', models.CharField(blank=True, max_length=200)),
                ('rank', models.CharField(blank=True, max_length=200)),
                ('totalteam', models.CharField(blank=True, max_length=200)),
                ('standing', models.URLField()),
            ],
        ),
    ]
