# Generated by Django 5.0.6 on 2024-06-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='projects/default1.png', upload_to='projects/')),
                ('cover', models.ImageField(blank=True, default='projects/default2.png', null=True, upload_to='projects/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('createdby', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True, max_length=200)),
                ('frontend', models.CharField(blank=True, max_length=200)),
                ('backend', models.CharField(blank=True, max_length=200)),
                ('desc', models.TextField(blank=True, max_length=300)),
            ],
        ),
    ]
