# Generated by Django 5.0.6 on 2024-06-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='createdby',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='projects',
            name='live_link',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='projects',
            name='source_code',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
