# Generated by Django 5.0.6 on 2024-06-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_createdby_projects_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='live_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='source_code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
