# Generated by Django 5.0.6 on 2024-06-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_projects_live_link_alter_projects_source_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='desc',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
