# Generated by Django 5.0.6 on 2024-06-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('short_desc', models.CharField(blank=True, max_length=300)),
                ('desc', models.TextField(blank=True, max_length=1000)),
                ('date', models.DateField(blank=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, default='blog/default.png', null=True, upload_to='blog/')),
                ('cover', models.ImageField(blank=True, default='blog/default.png', null=True, upload_to='blog/')),
            ],
        ),
    ]
