# Generated by Django 5.0.6 on 2024-06-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.ImageField(blank=True, default='default_cover.png', null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='cover',
            field=models.ImageField(blank=True, default='default_cover.png', null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='projects/'),
        ),
    ]
