# Generated by Django 5.0.6 on 2024-06-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_visitor_alter_blog_cover_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
