# Generated by Django 5.0.6 on 2024-06-19 19:04

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_visitor_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='desc',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
