# Generated by Django 5.0.6 on 2024-06-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_blog_desc_alter_projects_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='projects',
            name='desc',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
